### ISSUE TITLE
Error during git clone

### ISSUE THREAD

**Issue by jessemillar** [dxxb/sim-arduboy#1]
During installation, I hit an error while running `git clone --recursive https://github.com/dxxb/sim-arduboy.git`:
```
Cloning into 'sim-arduboy'...
remote: Counting objects: 44, done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 44 (delta 24), reused 38 (delta 20), pack-reused 0
Receiving objects: 100% (44/44), 15.91 KiB | 15.91 MiB/s, done.
Resolving deltas: 100% (24/24), done.
Submodule 'simavr' (git@github.com:dxxb/simavr-arduboy.git) registered for path 'simavr'
Cloning into '/Users/jessemillar/Documents/Projects/sim-arduboy/simavr'...
remote: Counting objects: 5864, done.        
remote: Total 5864 (delta 0), reused 0 (delta 0), pack-reused 5864        
Receiving objects: 100% (5864/5864), 4.33 MiB | 3.79 MiB/s, done.
Resolving deltas: 100% (3749/3749), done.
error: Server does not allow request for unadvertised object f10736a5aa410ff0818754c3d5635e9f0d9f05cd
Fetched in submodule path 'simavr', but it did not contain f10736a5aa410ff0818754c3d5635e9f0d9f05cd. Direct fetching of that commit failed.
```

`make` then fails (I'm assuming because the `clone` failed).
```
Makefile:34: simavr/examples/Makefile.opengl: No such file or directory
Makefile:44: simavr/Makefile.common: No such file or directory
make: *** No rule to make target `simavr/Makefile.common'.  Stop.
```

**Comment by dbrignoli** [comment]
Hi @jessemillar, the submodule's master branch was not up to date with _upstream_ thus the clone failed as you showed above. I have updated the submodule, an tested it here successfully. Please try again now.

**Comment by dxxb** [comment]
Hi @jessemillar, the submodule's master branch was not up to date with upstream thus the clone failed as you showed above. I have updated the submodule, an tested it here successfully. Please try again now.

**Comment by jessemillar** [comment]
The clone worked that time. Thank you!

**Comment by jessemillar** [comment]
I just got `sim-arduboy` fully up and running and it's beautiful! I don't yet own an Arduboy but this darn well might make me buy one.

**Comment by dxxb** [comment]
Great, if only I had a way or notifying the original creator of this issue >.<!
