### ISSUE TITLE
Freezing when sprites go off screen

### ISSUE THREAD

**Issue by jessemillar** [dxxb/sim-arduboy#2]
With the latest release, I'm getting some strange freezing when the police cars go off the screen in [this `.hex` file](https://github.com/jessemillar/crates/blob/ardbitmap/crates.ino.leonardo.hex) (press the "X" key on the menu to get to the game, use "X" to accelerate and the left and right arrows to turn). The freezing doesn't happen on the actual Arduboy. Any idea what's going on?

I'm using `sim_arduboy -p 3 ~/Documents/Projects/crates/crates.ino.leonardo.hex` to launch the emulator and followed the README instructions for installation exactly.

**Comment by dxxb** [comment]
I’ll look into this (probably tomorrow afternoon). FYI if you install avr-gdb you can start sim_arduboy with -d to connect to it and debug your AVR program. You can also (at the same time) use the host’s version of gdb to debug what happens in the emulator itself.

I suspect some kind of out of bound access which is caught and ignored on real h/w but results in a hard fault in simavr.

**Comment by dxxb** [comment]
I think I misunderstood your bug report. The emulator does not freeze in the sense that it stops working altogether. Instead, it looks like it slows down suddenly for less than a second and then goes back to normal. I can see it happening too but in my case it doesn't seem to be related to the police car going off screen. Main suspect at this point is SDL2 key repeat, I'll investigate.

**Comment by dxxb** [comment]
> Main suspect at this point is SDL2 key repeat, I'll investigate.

That's not it, other games I tried don't do it. Not sure what the cause is.

**Comment by jessemillar** [comment]
@dxxb I'm using [ArdBitmap](https://github.com/igvina/ArdBitmap) and it's been causing some slowdown issues for me. I wonder if the momentary freezing can be blamed on that. Apologies for not making my bug report more understandable. I probably should have provided a GIF capture.

**Comment by dxxb** [comment]
> I'm using ArdBitmap and it's been causing some slowdown issues for me. I wonder if the momentary freezing can be blamed on that.

I cannot rule it out but it doesn't seem likely. I was able to rule out an interrupt issue as well but I am not any closer to figuring this out. Would you agree that it happens (almost) exclusively when the player's car goes around in circles?

> Apologies for not making my bug report more understandable. I probably should have provided a GIF capture.

No worries, my bad: I made too many assumptions too quickly.

**Comment by jessemillar** [comment]
> Would you agree that it happens (almost) exclusively when the player's car goes around in circles?

Huh. It does look like it happens at least more often when the player's car is turning counter-clockwise. When I drive in counter-clockwise circles and the police cars go off the screen, it "freezes" pretty consistently.

To rule out any machine differences, here's a screenshot of my computer's specs. I've also uploaded the `sim_arduboy` binary I'm using.

[sim_arduboy.zip](https://github.com/dxxb/sim-arduboy/files/1865680/sim_arduboy.zip)
![screen shot 2018-03-31 at 11 38 46 am](https://user-images.githubusercontent.com/4627837/38165389-1480c5f4-34d8-11e8-8d94-37283107e94b.png)

**Comment by dxxb** [comment]
Hi @jessemillar, still no clue as to what is going on with your game. I was thinking to proceed by removing rendering of one game object at a time to find out at which point the issue appears. It will be a while before I can get around to trying that. In case you have time to try narrowing down which part of the code causes the slow down please go ahead, it would help a lot. Thanks

**Comment by jessemillar** [comment]
> I was thinking to proceed by removing rendering of one game object at a time to find out at which point the issue appears.

I've been trying to do this as time permits. My naive thought at this point is that it seems like a RAM issue. I'm moving away from `ArdBitmap` in favor of `Arduboy2`'s `Sprites` class and the issue seems to happen less often (I'm no longer using compressed sprites which should be less resource intensive). I'll keep investigating.

**Comment by jessemillar** [comment]
> My naive thought at this point is that it seems like a RAM issue.

If I change the number of police cars from 5 to 3, the stuttering problem disappears. I'm wondering if there's an issue with the way I'm calculating draw position relating to the camera: `sprites.drawSelfMasked((int16_t) (x - camera.x), (int16_t) (y - camera.y), sprite, frame);`. Maybe the subtraction mixed with casting takes up more memory suddenly when objects go off the screen. Regardless, this definitely seems more like an issue with my game than your emulator so I'm going to close this issue.
