### ISSUE TITLE
Linking with libsimavr on Linux

### ISSUE THREAD

**Issue by dlancer** [dxxb/sim-arduboy#6]
Current Makefile use dynamic linking, so before we can run `sim_arduboy`, compiled libsimavr library  should be installed to system, because at least Ubuntu 18.04 still have outdated libsimavr package in the repository without atmega32u4 support. 

There is also two possible solutions without library installation:
1. library path  setup
``` ShellSession
> LD_LIBRARY_PATH=path_to_directory_with_complied_libsimavr ./sim_arduboy app.hex
```
2. static linking 
```Makefile
LDFLAGS += -L${simavr}/${SIMAVR-OBJ} -l:libsimavr.a
```
Not sure if this should be mentioned to README or Makefile should be updated for Linux build...

**Comment by dxxb** [comment]
I have to look into this before I make a decision but this is what I am thinking right now: by default I'd like sim-arduboy to link statically to the version of libsimavr it comes bundled with. If one day we added support for DEB packages then dynamic linking (with the right libsimavr version dependency) would make sense.

**Comment by dlancer** [comment]
I can update my PR https://github.com/dxxb/sim-arduboy/pull/4 for static linking if you agree.

**Comment by dlancer** [comment]
Sure, no problem.
