### ISSUE TITLE
.gitignore and .editorconfig

### ISSUE THREAD

**Issue by dlancer** [dxxb/sim-arduboy#8]
If these files (.gitignore and .editorconfig) will be in repository. I can create initial versions if nobody is against it :)

**Comment by dxxb** [comment]
I'm ok with .gitignore of course but I think .editorconfig should be in your personal fork for the time being. Thank you.

**Comment by dlancer** [comment]
ok, PR https://github.com/dxxb/sim-arduboy/pull/9 added

**Comment by dxxb** [comment]
PR #9 merged, I'm closing this issue.
